# Generated by Django 4.0.7 on 2023-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_address_user_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
